[tool.commitizen]
version = "1.0.0"
name = "cz_conventional_commits"
version_files = ["Src/version.h:MAJOR_VERSION",
                 "Src/version.h:MINOR_VERSION",
                 "Src/version.h:PATCH_VERSION"]
version_provider = "commitizen"
version_scheme = "semver2"
tag_format = "$version"
update_changelog_on_bump = true
gpg_sign = false
annotated_tag = false
retry_after_failure = false
changelog_file = "CHANGELOG.md"
use_shortcuts = true
prerelease_offset = 1
major_version_zero = false
pre_bump_hooks = []
post_bump_hooks = []
encoding = "utf-8"